spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skydive_forecast_location_db
    username: skydive_forecast_location
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: skydive_forecast_location
    show-sql: true
  liquibase:
    enabled: true
    default-schema: skydive_forecast_location

logging:
  level:
    root: INFO

jwt:
  secret: hK8nX2mP9qR5vT3wL7bE4jY6cA1dF8sZ
